#====================================================================================================================#
# Android Application config
#====================================================================================================================#
isForceToInstallAPK: "false"